export default {
  Sanhua: 'Sanhua',
  BaiLian: 'Baizhi',
  Lingyang: 'Lingyang',
  Maxiaofang: 'Chixia',
  Anke: 'Encore',
  Baer: 'Mortefi',
  Kakaluo: 'Calcharo',
  Yinlin: 'Yinlin',
  Yuanwu: 'Yuanwu',
  Yangyang: 'Yangyang',
  Qiushui: 'Aalto',
  Jiyan: 'Jiyan',
  Jianxin: 'Jianxin',
  Jueyuan: 'Verina',
  Taohua: 'Taoqi',
  Micai: 'Danjin',
  DarkNvzhu: 'Rover(Havoc)',
  Nvzhu: 'Rover(Spectro)',
  DarkNanzhu: 'Rover(Havoc)',
  Nanzhu: 'Rover(Spectro)',

  Jinxi: 'Jinhsi',
  ChangLi: 'Changli',
  Zhezhi: 'Zhezhi',
} satisfies KnownCharacterNameMap;
