export default {
  Sanhua: '산화',
  BaiLian: '설지',
  Lingyang: '능양',
  Maxiaofang: '치샤',
  Anke: '앙코',
  Baer: '모르테피',
  Kakaluo: '카카루',
  Yinlin: '음림',
  Yuanwu: '연무',
  Yangyang: '양양',
  Qiushui: '알토',
  Jiyan: '기염',
  Jianxin: '감심',
  Jueyuan: '벨리나',
  Taohua: '도기',
  Micai: '단근',
  DarkNvzhu: '방랑자(회절)',
  Nvzhu: '방랑자(인멸)',
  DarkNanzhu: '방랑자(회절)',
  Nanzhu: '방랑자(인멸)',

  Jinxi: '금희',
  ChangLi: '장리',
  Zhezhi: '절지',
} satisfies KnownCharacterNameMap;
